server:
  port: 8081

spring:
  datasource:
    platform: h2
    url: jdbc:h2:file:~/data/productDB
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
